language: c

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

cache:
    apt: true
    directories:
        - $HOME/.runtimes
        - $HOME/.venv
        - $HOME/.cache/pip
        - $HOME/wheelhouse

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes

    matrix:
        - TASK=documentation
        - TASK=check-format
        - TASK=check-coverage
        - TASK=check-pypy
        - TASK=check-py26
        - TASK=check-py35
        - TASK=check-py27
        - TASK=check-py33
        - TASK=check-py34

script:
    - make $TASK

matrix:
    exclude:
        - os: osx
          env: TASK=check-fakefactory052
        - os: osx
          env: TASK=check-fakefactory053
        - os: osx
          env: TASK=check-pytest26
        - os: osx
          env: TASK=check-pytest27
        - os: osx
          env: TASK=documentation
        - os: osx
          env: TASK=check-django17
        - os: osx
          env: TASK=check-django18
        - os: osx
          env: TASK=check-examples2
        - os: osx
          env: TASK=check-examples3
        - os: osx
          env: TASK=check-coverage
        - os: osx
          env: TASK=check-format
    fast_finish: true

notifications:
  email: false
